import { VERSION } from '../version'

export type HeaderStyle = 'js' | 'html'

export function generatedHeader(style: HeaderStyle, sourcePath: string | false | undefined): string {
  if (sourcePath === false) return ''

  const from = sourcePath ? ` from ${sourcePath}` : ''
  const lines = [
    `Generated by @getpromptui/core@${VERSION}${from}.`,
    `Do NOT edit by hand — overwritten on the next \`promptui compile\`.`,
  ]

  if (style === 'html') {
    return `<!--\n  ${lines.join('\n  ')}\n-->`
  }
  return `/*\n * ${lines.join('\n * ')}\n */`
}