import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { LIBRARY_ENTRIES, type LibraryEntry } from '../src/library'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const REPO_ROOT = join(ROOT, '..', '..')
const PKG = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

const PREAMBLE = `# PromptUI skill for Claude Code

You are an expert in the PromptUI DSL — an AI-native language that compiles semantic UI instructions into React or Vue component templates.

> Generated from \`@getpromptui/core@${PKG.version}\` registry. Do not hand-edit this file in a consumer project — copy it from \`node_modules/@getpromptui/core/skill.md\` after upgrading.

## What you know

### Packages

- \`@getpromptui/core\` — parser, resolver, emitters, CLI, library registry
- \`@getpromptui/ui\` — React component library (the default \`library/*\` component set)

### Compiler pipeline

\`\`\`
.promptui file → parse() → resolve() → emitReact() / emitVue() → JSX / Vue SFC
\`\`\`

- **parse** — tokenizes lines, builds a \`Document\` tree of \`Block\` nodes
- **resolve** — validates \`use\` paths against the library registry, validates \`lock\`/\`ban\`/\`allow\` tokens, validates \`variant:\` against registered variants, returns warnings
- **emit** — walks the tree; collects all components used; emits a single \`import { ... } from '@getpromptui/ui'\` block at the top; renders component markup with attrs derived from directives. Compiled output starts with a "Generated by ... — do not edit" header so a human or AI editing the wrong file knows where to make changes.

### Block syntax

\`\`\`
[BlockType:optionalName] {
  directive: value
  [ChildBlock] { directive: value }
}
\`\`\`

- Inline shorthand (single-directive only): \`[Title] { text: "Hello" }\`
- Comments: \`//\` or \`#\`
- Nested blocks inside an inline block are **not** supported — use multi-line form

### Directives

| Directive  | Purpose |
|------------|---------|
| \`use\`      | Library path → component: \`library/heroes/split\` → \`HeroSplit\`. Validated against registry. |
| \`variant\`  | Skin variant (e.g. \`destructive\`, \`outline\`). Only valid when the \`use\` entry declares \`variants\`. Emitted as \`variant="..."\` prop. |
| \`role\`     | Semantic role: \`landing-hero\`, \`interactive-form\`, \`pricing-section\` |
| \`goal\`     | Natural-language intent hint for AI/review |
| \`look\`     | Semantic style tokens: \`centered dark-gradient rounded\`. Emitted as \`className\`. |
| \`lock\`     | Frozen aspects: \`structure spacing hierarchy states layout base-style\` |
| \`allow\`    | What may change: \`text subtitle buttons image badge icon binding\` |
| \`ban\`      | Forbidden: \`invent-new-layout custom-css inline-styles extra-wrappers hierarchy-changes unapproved-components\` |
| \`states\`   | Descriptive variants: \`desktop tablet mobile\` / \`default hover disabled\` |
| \`text\`     | Literal text content |
| \`flow\`     | Interaction → handler: \`open-waitlist\` → \`onClick={openWaitlist}\` |
| \`bind\`     | Data binding: \`email\` → \`value={email} onChange={(v) => setEmail(v)}\` |
| \`each\`     | Repeat block: \`each: user in users\` → React \`{users.map((user, i) => ...)}\` / Vue \`v-for\`. Auto-adds \`<collection>: unknown[]\` to Props when wrapped. |
| \`if\`       | Conditional: \`if: hasError\` → React \`{hasError && (...)}\` / Vue \`v-if\`. Expression is opaque; consumer wires identifiers. |

**Priority rules:** \`lock\` > \`look\`, \`ban\` > \`allow\`

### Expressions in \`text:\`

Values wrapped in \`{{ }}\` are emitted as JS expressions. Unwrapped values are string literals.

- \`text: "Hello"\` → \`{"Hello"}\` (React) / \`Hello\` (Vue)
- \`text: {{user.name}}\` → \`{user.name}\` (React) / \`{{ user.name }}\` (Vue)

This is required for referencing the iteration variable from \`each:\` in child blocks.

### \`variant:\` vs new file — the rule

- **Same markup, different skin** → use \`variant:\` on the existing \`use\` path.
- **Different markup, structure, or HTML element** → pick a different \`use\` path (e.g. \`library/inputs/password\` vs \`library/inputs/search\`).

Example: \`[Button] { use: library/buttons/default  variant: destructive }\` — correct.
Counter-example: writing \`variant: "with-icon"\` on a regular input is wrong — use \`library/inputs/withIcon\` instead.

### Sub-parts

Compound components expose sub-parts (see catalog below). Reference them as nested blocks **without** \`use\` — the resolver recognizes them by \`blockType\` and the emitter imports them automatically:

\`\`\`
[Section] {
  use: library/cards/default
  [CardHeader] {
    [CardTitle] { text: "Pricing" }
  }
  [CardContent] { ... }
}
\`\`\`

This resolves to:

\`\`\`jsx
import { CardContent, CardDefault, CardHeader, CardTitle } from '@getpromptui/ui'

<CardDefault>
  <CardHeader>
    <CardTitle>{"Pricing"}</CardTitle>
  </CardHeader>
  <CardContent>...</CardContent>
</CardDefault>
\`\`\`

### CLI

\`\`\`bash
npx promptui compile <file.promptui> --target react
npx promptui compile <file.promptui> --target vue
npx promptui compile <file.promptui> --export Signup   # wrap as \`export function Signup\`
\`\`\`

**Wrapping (React).** When \`--export <Name>\` is passed (or the root block has \`:Name\` like \`[Page:Signup]\`), the emitter outputs a complete \`.tsx\` file:

- \`export interface <Name>Props\` lists every \`flow:\` as \`on<Flow>?: () => void\`.
- The function body declares \`const [x, setX] = useState('')\` for every unique \`bind:\`.
- All library imports are grouped at the top (plus \`useState\` from \`react\` if needed).

Without a name or flag, the emitter falls back to a bare JSX fragment (back-compat mode for embedding into a larger file).

### Programmatic API

\`\`\`ts
import { compile, LIBRARY_ENTRIES, lookupByUse, VERSION } from '@getpromptui/core'

const { output, warnings } = compile(source, { target: 'react' })
\`\`\`

Low-level primitives:

\`\`\`ts
import { parse, resolve, emitReact, emitVue } from '@getpromptui/core'
\`\`\`
`

const HOW_TO_HELP = `
## How to help users

When the user asks you to:

- **Write a \`.promptui\` file** — produce valid block syntax. Pick the most specific \`use\` path (e.g. \`library/inputs/password\`, not \`library/inputs/default\` + \`type="password"\`). Use sub-parts as nested blocks. Use \`variant:\` only when the entry declares variants.
- **Compile** — run \`npx promptui compile <file> --target react|vue\` or use the programmatic \`compile(source, { target })\`.
- **Extend the compiler** — new emitters in \`packages/core/src/emitters/\`, new components in \`packages/ui/src/{category}/{Variant}.tsx\`. Add an entry to \`packages/core/src/library.ts\` and re-export from \`packages/ui/src/index.ts\`. Rebuild with \`pnpm build\`.
- **Debug a parse error** — \`ParseError\` includes the line number; check for missing \`{\`, mismatched \`}\`, invalid block header, or inline blocks with nested blocks (not supported).
- **Understand a warning** — resolver warns on: unknown \`use\` path, unknown \`lock\`/\`ban\` token, conflicting \`lock\`/\`look\` or \`ban\`/\`allow\`, unknown \`variant:\` value, \`variant:\` without a valid \`use\`.

## Examples

### Landing hero with CTA

\`\`\`
[Hero:main] {
  role: landing-hero
  use: library/heroes/split
  lock: structure spacing
  allow: text buttons

  [HeroSplitContent] {
    [HeroEyebrow]  { text: "Now in beta" }
    [HeroTitle]    { text: "Ship faster with PromptUI" }
    [HeroSubtitle] { text: "AI-native DSL for frontend templates." }
    [HeroActions] {
      [CTA:get] {
        use: library/buttons/default
        text: "Get started"
        flow: open-docs
      }
      [CTA:docs] {
        use: library/buttons/default
        variant: outline
        text: "Read docs"
      }
    }
  }

  [HeroSplitVisual] {
    [Placeholder] { use: library/skeletons/card }
  }
}
\`\`\`

### Site-wide page chrome

\`\`\`
[Page:HomePage] {
  use: library/layouts/main

  [Header] {
    use: library/headers/default
    variant: sticky
    [HeaderBrand]   { text: "Acme" }
    [HeaderNav]     { /* nav links */ }
    [HeaderActions] { /* CTAs */ }
  }

  [Content] {
    use: library/layouts/section
    /* page sections go here */
  }

  [Footer] {
    use: library/footers/default
    variant: columns
    [FooterColumns] {
      [FooterColumn] {
        [FooterColumnTitle] { text: "Product" }
        [FooterLinks] {
          [FooterLink] { text: "Pricing" }
          [FooterLink] { text: "Docs" }
        }
      }
    }
    [FooterBottom] {
      [FooterCopyright] { text: "© 2026 Acme" }
    }
  }
}
\`\`\`

### Signup card with error state

\`\`\`
[Section:signup] {
  use: library/cards/default
  role: signup-card
  allow: text buttons

  [CardHeader] {
    [CardTitle]       { text: "Join the waitlist" }
    [CardDescription] { text: "Ping me when it ships." }
  }
  [CardContent] {
    [Email] { use: library/inputs/email  bind: email }
    [Err] {
      use: library/alerts/default
      variant: destructive
      [AlertTitle]       { text: "Invalid email" }
      [AlertDescription] { text: "Please provide a valid address." }
    }
  }
  [CardFooter] {
    [Submit] {
      use: library/buttons/loading
      text: "Notify me"
      flow: submit-waitlist
    }
  }
}
\`\`\`

Each example above compiles cleanly to both React and Vue with imports collected at the top. No warnings if directives and \`use\` paths are used correctly.
`

function categoryOf(use: string): string {
  return use.split('/')[1] ?? 'misc'
}

function variantSegment(use: string): string {
  return use.split('/').slice(2).join('/') || 'default'
}

function entryLine(entry: LibraryEntry): string {
  const variantStr = entry.variants?.length
    ? ` · variants: ${entry.variants.map(v => `\`${v}\``).join(', ')}`
    : ''
  const partsStr = entry.parts.length
    ? `  \n  Parts: ${entry.parts.map(p => `\`${p}\``).join(', ')}`
    : ''
  return `- \`${entry.use}\` → \`${entry.main}\`${variantStr}${partsStr}`
}

function buildCatalog(): string {
  const byCategory = new Map<string, LibraryEntry[]>()
  for (const e of LIBRARY_ENTRIES) {
    const cat = categoryOf(e.use)
    const arr = byCategory.get(cat) ?? []
    arr.push(e)
    byCategory.set(cat, arr)
  }

  for (const arr of byCategory.values()) {
    arr.sort((a, b) => variantSegment(a.use).localeCompare(variantSegment(b.use)))
  }

  const sortedCategories = [...byCategory.keys()].sort()
  const total = LIBRARY_ENTRIES.length

  const lines: string[] = []
  lines.push('## Component library catalog')
  lines.push('')
  lines.push(`${total} \`use\`-paths registered. All import from \`@getpromptui/ui\`.`)
  lines.push('')

  for (const cat of sortedCategories) {
    lines.push(`### \`${cat}/\``)
    for (const entry of byCategory.get(cat)!) {
      lines.push(entryLine(entry))
    }
    lines.push('')
  }
  return lines.join('\n')
}

function main() {
  const catalog = buildCatalog()
  const out = `${PREAMBLE}\n${catalog}\n${HOW_TO_HELP}`

  // 1. Ship inside the package as @getpromptui/core/skill.md
  writeFileSync(join(ROOT, 'skill.md'), out)

  // 2. Refresh the repo's own .claude/commands/promptui.md so this repo's
  //    Claude sessions and the README's curl link both stay in sync.
  const claudeDir = join(REPO_ROOT, '.claude', 'commands')
  if (!existsSync(claudeDir)) mkdirSync(claudeDir, { recursive: true })
  writeFileSync(join(claudeDir, 'promptui.md'), out)

  console.log(`generate-skill: wrote skill.md (${LIBRARY_ENTRIES.length} entries) → packages/core/skill.md + .claude/commands/promptui.md`)
}

main()